#!/bin/sh

echo "cmd input - $1"
# shellcheck disable=SC1046
  if [ "$1" == 'start' ]
    then
        echo "deploying docker images..."
        mvn clean install -DskipTests
        docker image rm docker-demo
        docker-compose up
  fi
  if [ "$1" == 'stop' ]
    then
      echo "stopping docker containers..."
      docker-compose down
  fi